#!/usr/bin/env python3
"""
Generates XOR-obfuscated native secret sources from the local .env API token.

Defaults to iOS for backward compatibility with the existing Xcode pre-build
phase, and also supports Android generation via --platform android.
"""

import argparse
import os
import sys

def parse_dotenv(path):
    env = {}
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, _, value = line.partition('=')
                    env[key.strip()] = value.strip()
    except FileNotFoundError:
        print(f"error: .env file not found at {path}")
        print("error: Copy .env.example to .env and fill in your PANDASCORE_TOKEN")
        sys.exit(1)
    return env

def compute_mask(length):
    """Deterministic mask derived from seed — not stored as array in binary."""
    seed = 0xCAFEBABE
    mask = []
    for _ in range(length):
        seed = (seed * 6364136223846793005 + 1) & 0xFFFFFFFF
        mask.append((seed >> 16) & 0xFF)
    return mask

def parse_args(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--platform',
        choices=('ios', 'android'),
        default='ios',
        help='Native target to generate secret source for.'
    )
    return parser.parse_args(argv)

def render_obfuscated_bytes(obfuscated):
    return ', '.join(f'0x{b:02X}' for b in obfuscated)

def ios_output_path(project_root):
    return os.path.join(
        project_root,
        'csgo-leagues-ios', 'csgo-leagues-ios', 'Core', 'Secrets', 'secrets.c'
    )

def android_output_path(project_root):
    return os.path.join(
        project_root,
        'csgo-leagues-android', 'app', 'src', 'main', 'cpp', 'secrets.cpp'
    )

def generate_ios_source(obfuscated):
    c_bytes = render_obfuscated_bytes(obfuscated)
    return f'''// Auto-generated by scripts/generate_secrets.py --platform ios — DO NOT COMMIT
// This file is git-ignored.
#include "secrets.h"
#include <stdlib.h>

static const unsigned char _t[] = {{ {c_bytes} }};
static const int _tl = {len(obfuscated)};

const char* get_api_token(void) {{
    char* result = (char*)malloc(_tl + 1);
    if (!result) return "";
    unsigned int seed = 0xCAFEBABE;
    for (int i = 0; i < _tl; i++) {{
        seed = (unsigned int)(seed * 6364136223846793005ULL + 1);
        result[i] = _t[i] ^ ((seed >> 16) & 0xFF);
    }}
    result[_tl] = '\\0';
    return result;
}}
'''

def generate_android_source(obfuscated):
    c_bytes = render_obfuscated_bytes(obfuscated)
    return f'''// Auto-generated by scripts/generate_secrets.py --platform android — DO NOT COMMIT
// This file is git-ignored.
#include <jni.h>

static const unsigned char _t[] = {{ {c_bytes} }};
static const int _tl = {len(obfuscated)};

extern "C"
JNIEXPORT jstring JNICALL
Java_com_voidx_csgo_core_Secrets_getApiToken(JNIEnv* env, jobject /* this */) {{
    char result[_tl + 1];
    unsigned int seed = 0xCAFEBABE;
    for (int i = 0; i < _tl; i++) {{
        seed = (unsigned int)(seed * 6364136223846793005ULL + 1);
        result[i] = _t[i] ^ ((seed >> 16) & 0xFF);
    }}
    result[_tl] = '\\0';
    return env->NewStringUTF(result);
}}
'''

def write_output(out_path, source):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write(source)

def main():
    args = parse_args(sys.argv[1:])

    # Find project root (script is in scripts/ dir)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    env_path = os.path.join(project_root, '.env')

    env = parse_dotenv(env_path)
    token = env.get('PANDASCORE_TOKEN', '')

    if not token or token == 'your_token_here':
        print("error: PANDASCORE_TOKEN is not set in .env")
        print("error: Copy .env.example to .env and fill in your API token")
        sys.exit(1)

    mask = compute_mask(len(token))
    obfuscated = [ord(c) ^ mask[i] for i, c in enumerate(token)]

    if args.platform == 'android':
        out_path = android_output_path(project_root)
        source = generate_android_source(obfuscated)
    else:
        out_path = ios_output_path(project_root)
        source = generate_ios_source(obfuscated)

    write_output(out_path, source)

    print(f"Generated {out_path}")

if __name__ == '__main__':
    main()
